services:
  - type: web
    name: abd666
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn abd66.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: django-insecure-REPLACE_THIS_WITH_A_STRONG_SECRET_KEY
      - key: ALLOWED_HOSTS
        value: abd666.onrender.com,127.0.0.1,localhost
      - key: DATABASE_URL
        fromDatabase:
          name: abd666-db
          property: connectionString
      - key: CLOUDINARY_CLOUD_NAME
        value: dcoutuiif
      - key: CLOUDINARY_API_KEY
        value: 713926589539725
      - key: CLOUDINARY_API_SECRET
        value: IYgGlpoD5CmUv5fR4GTYTnpJZHs
